plugins:
    tags_displaying_gallery:
        default: ""
        client: true
    desktop_picture_width:
        default: 200
        client: true
    mobile_picture_width:
        default: 50
        client: true
